export interface Platform {
  id: string;
  name: string;
  logoUrl: string;
}

export const PLATFORMS: Platform[] = [
  { id: "discord", name: "Discord", logoUrl: "https://cdn.simpleicons.org/discord" },
  { id: "instagram", name: "Instagram", logoUrl: "https://cdn.simpleicons.org/instagram" },
  { id: "roblox", name: "Roblox", logoUrl: "https://cdn.simpleicons.org/roblox/white" },
  { id: "spotify", name: "Spotify", logoUrl: "https://cdn.simpleicons.org/spotify" },
  { id: "soundcloud", name: "SoundCloud", logoUrl: "https://cdn.simpleicons.org/soundcloud" },
  { id: "steam", name: "Steam", logoUrl: "https://cdn.simpleicons.org/steam/4682B4" },
  { id: "tiktok", name: "TikTok", logoUrl: "https://cdn.simpleicons.org/tiktok/white" },
  { id: "x", name: "X", logoUrl: "https://cdn.simpleicons.org/x" },
  { id: "youtube", name: "YouTube", logoUrl: "https://cdn.simpleicons.org/youtube" },
  { id: "twitch", name: "Twitch", logoUrl: "https://cdn.simpleicons.org/twitch" },
  { id: "github", name: "GitHub", logoUrl: "https://cdn.simpleicons.org/github/white" },
  { id: "snapchat", name: "Snapchat", logoUrl: "https://cdn.simpleicons.org/snapchat" },
  { id: "reddit", name: "Reddit", logoUrl: "https://cdn.simpleicons.org/reddit" },
  { id: "threads", name: "Threads", logoUrl: "https://cdn.simpleicons.org/threads/white" },
  { id: "bluesky", name: "Bluesky", logoUrl: "https://cdn.simpleicons.org/bluesky" },
  { id: "telegram", name: "Telegram", logoUrl: "https://cdn.simpleicons.org/telegram" },
  { id: "whatsapp", name: "WhatsApp", logoUrl: "https://cdn.simpleicons.org/whatsapp" },
  { id: "facebook", name: "Facebook", logoUrl: "https://cdn.simpleicons.org/facebook" },
  { id: "linkedin", name: "LinkedIn", logoUrl: "https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" },
  { id: "pinterest", name: "Pinterest", logoUrl: "https://cdn.simpleicons.org/pinterest" },
  { id: "patreon", name: "Patreon", logoUrl: "https://cdn.simpleicons.org/patreon" },
  { id: "kick", name: "Kick", logoUrl: "https://cdn.simpleicons.org/kick" },
  { id: "bandcamp", name: "Bandcamp", logoUrl: "https://cdn.simpleicons.org/bandcamp" },
  { id: "applemusic", name: "Apple Music", logoUrl: "https://cdn.simpleicons.org/applemusic/white" },
  { id: "deezer", name: "Deezer", logoUrl: "https://cdn.simpleicons.org/deezer" },
  { id: "signal", name: "Signal", logoUrl: "https://cdn.simpleicons.org/signal" },
  { id: "medium", name: "Medium", logoUrl: "https://cdn.simpleicons.org/medium/white" },
  { id: "devto", name: "Dev.to", logoUrl: "https://cdn.simpleicons.org/devdotto/white" },
  { id: "gitlab", name: "GitLab", logoUrl: "https://cdn.simpleicons.org/gitlab" },
  { id: "codepen", name: "CodePen", logoUrl: "/company-logos/codepen-white.svg" },
  { id: "stackoverflow", name: "Stack Overflow", logoUrl: "https://cdn.simpleicons.org/stackoverflow" },
  { id: "etsy", name: "Etsy", logoUrl: "https://cdn.simpleicons.org/etsy" },
  { id: "tumblr", name: "Tumblr", logoUrl: "https://cdn.simpleicons.org/tumblr/white" },
  { id: "flickr", name: "Flickr", logoUrl: "https://cdn.simpleicons.org/flickr" },
  { id: "lastfm", name: "Last.fm", logoUrl: "https://cdn.simpleicons.org/lastdotfm" },
  { id: "letterboxd", name: "Letterboxd", logoUrl: "https://cdn.simpleicons.org/letterboxd" },
  { id: "imdb", name: "IMDb", logoUrl: "https://cdn.simpleicons.org/imdb" },
  { id: "goodreads", name: "Goodreads", logoUrl: "https://cdn.simpleicons.org/goodreads/white" },
  { id: "strava", name: "Strava", logoUrl: "https://cdn.simpleicons.org/strava" },
  { id: "kofi", name: "Ko-fi", logoUrl: "https://cdn.simpleicons.org/kofi" },
  { id: "buymeacoffee", name: "Buy Me a Coffee", logoUrl: "https://cdn.simpleicons.org/buymeacoffee" },
  { id: "gumroad", name: "Gumroad", logoUrl: "https://cdn.simpleicons.org/gumroad/white" },
  { id: "substack", name: "Substack", logoUrl: "https://cdn.simpleicons.org/substack" },
  { id: "nintendo", name: "Nintendo", logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Nintendo.svg" },
  { id: "playstation", name: "PlayStation", logoUrl: "https://cdn.simpleicons.org/playstation" },
  { id: "xbox", name: "Xbox", logoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Xbox_one_logo.svg" },
  { id: "epicgames", name: "Epic Games", logoUrl: "https://cdn.simpleicons.org/epicgames/white" },
  { id: "unity", name: "Unity", logoUrl: "https://cdn.simpleicons.org/unity/white" },
  { id: "fiverr", name: "Fiverr", logoUrl: "https://cdn.simpleicons.org/fiverr" },
  { id: "shopify", name: "Shopify", logoUrl: "https://cdn.simpleicons.org/shopify" },
  { id: "lichess", name: "Lichess", logoUrl: "https://cdn.simpleicons.org/lichess/white" },
];
